tap "fairwindsops/tap"
tap "fluxcd/tap"
tap "hashicorp/tap"
tap "infisical/get-cli"
tap "oven-sh/bun"

brew "argocd"
brew "awscli"
brew "bazelisk"
brew "fairwindsOps/tap/pluto"
brew "fluxcd/tap/flux"
brew "hashicorp/tap/vault"
brew "helm"
brew "infisical/get-cli/infisical"
brew "istioctl"
brew "k9s"
brew "krew"
brew "kubecm"
brew "kubernetes-cli@1.31"
brew "mongosh"
brew "oven-sh/bun/bun"
brew "skopeo"
brew "sqlc"
brew "stern"
brew "tenv"
brew "vultr"

cask "session-manager-plugin"
