tap "hashicorp/tap"
tap "danielfoehrkn/switch"

brew "argocd"
brew "awscli"
brew "bazelisk"
brew "danielfoehrkn/switch/switch"
brew "hashicorp/tap/vault"
brew "helm"
brew "istioctl"
brew "k9s"
brew "krew"
brew "kubernetes-cli@1.31"
brew "sqlc"
brew "stern"
brew "tofuutils/tap/tofuenv"
cask "session-manager-plugin"
