local pick_to_close = function()
  require("astronvim.utils.status").heirline.buffer_picker(function(bufnr) require("astronvim.utils.buffer").close(bufnr) end)
end

return {
  n = {
    ["a"]                 = { "0" },
    ["A"]                 = { "$" },
    ["cn"]                = { "*``cgn" }, -- https://www.kevinli.co/posts/2017-01-19-multiple-cursors-in-500-bytes-of-vimscript/
    ["cr"]                = { "<cmd>GitConflictRefresh<cr>", desc = "Git conflict: Refresh" },
    ["E"]                 = { "ge" },
    ["s"]                 = false,
    ["W"]                 = { "b" },
    ["<C-c>"]             = { "<cmd>startinsert<cr>" },
    ["<Tab>"]             = { "<cmd>bn<cr>" },
    ["<S-Tab>"]           = { "<cmd>bN<cr>" },
    ["<leader>h"]         = false,
    ["<leader>q"]         = false,
    ["<leader>o"]         = { "<cmd>Oil<cr>", desc = "Oil file manager" },
    ["<leader>bn"]        = { "<cmd>tabnew<cr>", desc = "New tab" },
    ["<leader>bD"]        = { pick_to_close, desc = "Pick to close" },
    ["<leader>G"]         = { desc = "Github" },
    ["<leader>GI"]        = { desc = "Issue search" },
    ["<leader>GP"]        = { desc = "PR search" },
    ["<leader>Ga"]        = { desc = "Assignee" },
    ["<leader>Gc"]        = { desc = "Comment" },
    ["<leader>Gi"]        = { desc = "Action" },
    ["<leader>Gl"]        = { desc = "Label" },
    ["<leader>Gp"]        = { desc = "Git action" },
    ["<leader>Gr"]        = { desc = "Reaction" },
    ["<leader>Gs"]        = { desc = "Suggestion" },
    ["<leader>Gv"]        = { desc = "Reviewer" },
    ["<leader>GIc"]       = { "<cmd>Octo issue search is:closed<cr>", desc = "Closed" },
    ["<leader>GIm"]       = { "<cmd>Octo issue search is:open author:@me<cr>", desc = "My issues" },
    ["<leader>GIo"]       = { "<cmd>Octo issue search is:open<cr>", desc = "Open" },
    ["<leader>GIp"]       = { ":Octo issue ", desc = "Prefill" },
    ["<leader>GPc"]       = { "<cmd>Octo pr search is:closed<cr>", desc = "Closed" },
    ["<leader>GPm"]       = { "<cmd>Octo pr search is:open author:@me<cr>", desc = "My PR" },
    ["<leader>GPn"]       = { "<cmd>Octo pr search is:open user-review-requested:@me<cr>", desc = "Need review" },
    ["<leader>GPo"]       = { "<cmd>Octo pr search is:open<cr>", desc = "Open" },
    ["<leader>GPp"]       = { ":Octo pr ", desc = "Prefill" },
    ["<leader>M"]         = { desc = " Markdown" },
    ["<leader>Ma"]        = { "<cmd>GenTocGFM<cr>", desc = "Add TOC" },
    ["<leader>Mu"]        = { "<cmd>UpdateToc<cr>", desc = "Update TOC" },
    ["<leader>S"]         = { desc = "󱂬 Session"},
    ["<leader>Sc"]        = { "<cmd>PossessionClose<cr>", desc = "Close this session" },
    ["<leader>Sd"]        = { "<cmd>PossessionDelete<cr>", desc = "Delete this session" },
    ["<leader>Sl"]        = { "<cmd>Telescope possession list<cr>", desc = "Load session" },
    ["<leader>Sr"]        = { "<cmd>PossessionRename<cr>", desc = "Rename this session" },
    ["<leader>Ss"]        = { ":PossessionSave untitled", desc = "Save this session" },
    ["<leader>h"]         = { desc = "✈ Hop" },
    ["<leader>hl"]        = { "<cmd>HopLineStart<cr>", desc = "Hop Line Start" },
    ["<leader>hp"]        = { "<cmd>HopPattern<cr>", desc = "Hop Pattern" },
    ["<leader>hn"]        = { "<cmd>HopWordAC<cr>" , desc = "Hop word after current line" },
    ["<leader>hN"]        = { "<cmd>HopWordBC<cr>" , desc = "Hop word before current line" },
    ["<leader>hw"]        = { "<cmd>HopWord<cr>", desc = "Hop Word" },
    ["<leader>m"]         = { desc = "⚑ Marks" },
    ["<leader>mS"]        = { "<cmd>MarksListAll<cr>", desc = "Show marks in all buffers" },
    ["<leader>mc"]        = { "<Plug>(Marks-deletebuf)", desc = "Clear marks in current buffer" },
    ["<leader>ms"]        = { "<cmd>MarksListBuf<cr>", desc = "Show marks in current buffer" },
    ["<leader>tf"]        = { "<cmd>ToggleTerm direction=float dir=%:h:p<cr>", desc = "ToggleTerm float" },
    ["<leader>t<bslash>"] = { "<cmd> silent !tmux split-window -v -c %:p:h<cr>", desc = "Tmux vertical split" },
    ["<leader>t|"]        = { "<cmd> silent !tmux split-window -h -c %:p:h<cr>", desc = "Tmux horizontal split" },
    ["<leader>tw"]        = { "<cmd> silent !tmux new-window -c %:p:h<cr>", desc = "Tmux new window" },
    ["<leader>tH"]        = { "<cmd>ToggleTerm size=10 direction=horizontal dir=%:h:p<cr>", desc = "ToggleTerm horizontal split" },
    ["<leader>tV"]        = { "<cmd>ToggleTerm size=80 direction=vertical dir=%:h:p<cr>", desc = "ToggleTerm vertical split" },
    ["<leader>x"]         = { desc = "⚠ Trouble" },
    ["<leader>xX"]        = { "<cmd>TroubleToggle workspace_diagnostics<cr>", desc = "Workspace Diagnostics" },
    ["<leader>xl"]        = { "<cmd>TroubleToggle loclist<cr>", desc = "Location List" },
    ["<leader>xx"]        = { "<cmd>TroubleToggle document_diagnostics<cr>", desc = "Document Diagnostics" },
    ["<leader>Y"]         = { "<cmd>Telescope neoclip default extra=star,plus<cr>" , desc = "Yank History" },
  },
  x = {
    ["<leader>:"]         = { "<cmd>Tab/:<cr>", desc = "Tabularize :" },
    ["<leader><bslash>"]  = { "<cmd>Tab/<bar><cr>", desc = "Tabularize |" },
    ["<leader>="]         = { "<cmd>Tab/=<cr>", desc = "Tabularize =" },
    ["cn"]                = { [[g:mc . "``cgn"]], expr = true }
  },
}
